=== geosone/vc/help/guide.dtd
<!-- Copyright 2026 Mario Fetka. SPDX-License-Identifier: BSD-2-Clause -->
<!ELEMENT guide (credits, topic+)>
<!ATTLIST guide language CDATA #REQUIRED codepage CDATA #REQUIRED
          original CDATA #IMPLIED original-sha256 CDATA #IMPLIED>
<!ELEMENT credits (credit*)>
<!ELEMENT credit (#PCDATA)>
<!ELEMENT topic (title, (p | heading | pre | line)*)>
<!ATTLIST topic id ID #REQUIRED layout (prose | ng) "prose">
<!ELEMENT title (#PCDATA | char)*>
<!ELEMENT p (#PCDATA | b | u | code | char)*>
<!ELEMENT heading (#PCDATA | b | u | code | char)*>
<!ELEMENT b (#PCDATA | u | code | char)*>
<!ELEMENT u (#PCDATA | b | code | char)*>
<!ELEMENT code (#PCDATA | char)*>
<!ELEMENT pre (#PCDATA | char)*>
<!ELEMENT line (#PCDATA | char)*>
<!ELEMENT char EMPTY>
<!ATTLIST char code CDATA #REQUIRED>

=== geosone/vc/help/src/sk.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="../guide.css"?>
<!DOCTYPE guide SYSTEM "../guide.dtd">
<guide language="sk" codepage="cp852" original="VC-SK.HLP" original-sha256="e619f01b3bb202c1b36b9c7f84b2c1d35c3be7c6f44cffceb6b0a112a736e068">
  <credits>
    <credit>Copyright (C) 1991-2000 by Vsevolod V. Volkov</credit>
    <credit />
    <credit />
    <credit />
    <credit />
  </credits>
  <topic id="release" layout="prose">
    <title>Verzia a nové funkcie</title>
    <p>Pomoc opisuje Volkov Commander {{version}}. Program vychádza zo zverejnených zdrojov 4.99.09 a pridáva pomoc F1, nový systém zostavenia a malé rozšírenia. Konečné vydanie 5.0 sa pripravuje; táto vývojová verzia ešte nie je finálnym vydaním 5.0.</p>
    <p>F1 otvorí pomoc aktuálneho okna. V súborových paneloch otvorí zoznam tém. Enter vyberá tému, Next a Previous menia tému, Index vracia zoznam, Escape zatvára pomoc.</p>
    <p>F2 a potom F3 otvorí rozšírenia: archívy, zoznamy súborov, hromadné príkazy, rozpoznanie formátu a hexadecimálny náhľad. Úplné ZIP vydanie obsahuje stiahnuté archivátory; disketa 1,44 MB len VC a vlastné nástroje. Referenčné kapitoly boli aktualizované pre menu, klávesy a nastavenia 4.99.10.</p>
  </topic>
  <topic id="menus" layout="prose">
    <title>Menu a nové makrá</title>
    <p>F2 otvorí používateľské menu, v ňom F3 rozšírenia a F1 archívne menu. Shift-F2 otvorí hlavné menu aj pri miestnom VC.MNU. Escape zatvára menu, F10 vracia nadradené menu uvedené pri príslušnej položke.</p>
    <p>Súbory .MNU sú textové: kláves a názov položky, potom odsadené príkazy alebo názov ďalšieho menu. Aktualizácia zachováva existujúce menu. Do staršieho VC.MNU môže byť potrebné doplniť položku addons.mnu.</p>
    <p>! a !.! označujú aktuálny názov bez prípony a s príponou. !@ označuje dočasný zoznam označených súborov; bez označenia sa použije aktuálny súbor. Tvary s % sa týkajú druhého panela. !~.! a !~@ používajú krátke názvy DOS. ![Otázka] vyžiada text, !0...!9 znovu použijú zadané odpovede.</p>
    <p>Nové !$ a %$ poskytujú inštalačný adresár VC s koncovým spätným lomítkom. Nástroje sa tak nájdu aj bez VC v PATH:</p>
    <pre>"!$VCTOOLS.EXE" type "!~.!"</pre>
  </topic>
  <topic id="archives" layout="prose">
    <title>Priložené archivátory</title>
    <p>make release stiahne DOS archivátory a nainštaluje ich vedľa VC. Menu používa inštalačný adresár; netreba samostatne nastavovať PATH. ZIP.EXE a UNZIP.EXE sú 16-bitový Info-ZIP. Samostatné menu PKZIP používa pôvodné shareware programy PKZIP/PKUNZIP 2.50.</p>
    <p>ARJ 2.78 Open-Source vytvára, zobrazuje, testuje a rozbaľuje ARJ. ACE 1.2b je shareware s 30-dňovou skúšobnou lehotou. RAR 2.06 vytvára staré RAR2, skúšobná lehota je 40 dní. UNRAR 3.80 beta číta staršie RAR; na RAR5 použite Retro7Zip. LHA 2.13 spracúva LZH, ARC 6.02 a PKARC/PKXARC ARC.</p>
    <p>Vytvorenie zabalí označené súbory. Zobrazenie a test pracujú s aktuálnym archívom, rozbalenie zapisuje do adresára druhého panela. Otázky pri prepisovaní naďalej riadi archivátor.</p>
    <p>PACKDOC obsahuje licencie, návody, pôvodné balíky a potrebné zdroje. PACKERS.TXT uvádza verzie a pôvod. Cudzie programy si zachovávajú vlastné licencie; nevzťahuje sa na ne BSD licencia Commandera.</p>
  </topic>
  <topic id="retro7zip" layout="prose">
    <title>Retro7Zip a archívne panely</title>
    <p>Retro7Zip 24.09+5 beží pod DOS na procesore 386 alebo novšom. 7ZA má najviac formátov, 7ZR je menší, 7ZM je na jednoduché 7z a málo pamäte, 7ZDEC je minimálny rozbaľovač 7z. Nároky na pamäť závisia od archívu, kompresného slovníka a variantu programu.</p>
    <p>Menu vytvára 7z, ZIP, TAR a WIM. gzip, BZip2 a XZ komprimujú jeden vstupný súbor: označte iba tento súbor. Retro7Zip číta RAR5, ale nevytvára RAR. VCARCH.EXT spája archívne panely s programami. Enter otvorí archív ako adresár, F3 zobrazí súbor, F5 rozbalí označené súbory. Kopírovanie do zapisovateľného archívu pridá súbory. TAR.GZ má dve vrstvy: kompresiu a následne vnútorný súbor TAR.</p>
    <p>VC7Z prekladá technické zoznamy pre VC, aj pri solid archívoch. Chýbajúca samostatná zabalená veľkosť sa zobrazí ako 0. Chýbajúci dátum používa 01.01.1980. Polia veľkosti súborov vo VC sú 32-bitové. VC7Z rozbaľuje do existujúceho adresára a podľa potreby mení jednotku, čím obchádza chybu DOS verzie Retro7Zip. Príkaz 7ZA i ukáže formáty.</p>
  </topic>
  <topic id="lists" layout="prose">
    <title>Zoznamy a hromadné príkazy</title>
    <p>F2, F3, F4 otvorí zoznamy a príkazy pre označené súbory. N zapíše krátke názvy do VC.LST, L dlhé do VCLONG.LST, P úplné krátke cesty do VCPATH.LST. B vytvorí VCLIST.BAT s ECHO pre každý súbor. Existujúce výstupné súbory sa prepíšu.</p>
    <p>D ukáže náhľad príkazu, R ho vykoná. {} znamená názov súboru; každá náhrada sa vloží v úvodzovkách. Príklad: ATTRIB +R {}. Náhľad nič nevykoná. Prvá chyba zastaví spracovanie; skoršie príkazy sa nevrátia späť. Rozvinutý príkaz môže mať najviac 126 bajtov. Názvy s riadiacimi znakmi príkazového interpretera sa odmietnu.</p>
    <p>Zoznamy sa čítajú po riadkoch bez dodatočného prehľadávania podadresárov. Relatívne názvy vychádzajú z aktuálneho adresára. Na prístup DOS použite krátke názvy; zoznam dlhých názvov je textový výstup.</p>
    <pre>VCTOOLS list FILES.LST --full
VCTOOLS run FILES.LST "ECHO {}" --dry-run</pre>
  </topic>
  <topic id="helpers" layout="prose">
    <title>Formát súboru a hex náhľad</title>
    <p>T v menu rozšírení určí formát podľa úvodných bajtov, nielen prípony. Rozpoznáva bežné archívy, programy DOS/Windows a ELF, PDF, niektoré obrázky a WAV, prázdne súbory a jednoduchým odhadom text. Nejde o test neporušenosti súboru.</p>
    <p>H zobrazí prvých 256 bajtov ako hex a ASCII. V príkazovom riadku možno zadať začiatok a dĺžku. Je to iba čítanie, nie binárny editor ani úplná náhrada Hiew:</p>
    <pre>VCTOOLS hex PROGRAM.EXE 0x100 64</pre>
    <p>Z zobrazí obsah bežného ZIP bez archivátora. Číta adresár, nerozbaľuje a nekontroluje CRC. Malý prehliadač nepodporuje ZIP64 ani viacdielny ZIP. Viac formátov ponúka menu Retro7Zip. Znak &gt; presmeruje výstup do súboru. ADDONS.TXT obsahuje podrobnejší nemecký návod k rozšíreniam.</p>
  </topic>
  <topic id="os2" layout="prose">
    <title>Nástroje relácie DOS v OS/2</title>
    <p>Úplné vydanie obsahuje pôvodný AUTOINS.COM zo stránky VC. Zapína opakovanie klávesu Insert v relácii DOS pod OS/2. Spustite ho raz za reláciu z menu OS/2; inštalátor ho nepridáva do automatického spúšťania.</p>
    <p>Adresár OS2 obsahuje pôvodné ikony VC-WN.ICO pre okno, VC-FS.ICO pre celú obrazovku a ďalšie ikony VC. ZIP balíky sú v PACKDOC/OS2. Sú to pomôcky pre DOS verziu VC, nie natívne archivátory OS/2. Existujúca podpora rozšírených atribútov OS/2 zostáva zachovaná. Binárne opravy pre VC 4.00/4.01 nie sú určené pre túto verziu.</p>
  </topic>
  <topic id="install" layout="prose">
    <title>Inštalácia a licencie</title>
    <p>Spustite INSTALL v adresári vydania, vyberte cieľ a jazyk pomoci. Navrhnutý jazyk vychádza z COUNTRY= v CONFIG.SYS. Zvolená pomoc sa uloží vedľa programu ako VC.HLP.</p>
    <p>Pred kopírovaním úplné vydanie vyžaduje prijatie všetkých licencií archivátorov. Deväť dialógov pokrýva VC a cudzie programy; súvisiace texty sú spojené. Odmietnutie zruší inštaláciu. Pôvodné podmienky, návody a zdroje zostávajú v PACKDOC.</p>
    <p>INSTALL /S použije automatické odpovede GDI a prijme licencie automaticky. Bez /S sa zobrazia otázky. Zápis PATH a ikona Správcu programov Windows sú voliteľné.</p>
    <p>Aktualizácie zachovajú VC.INI a vlastné .MNU/.EXT. Staršie menu môže potrebovať položku addons.mnu. INSTALL /U z inštalovaného adresára spustí odinštalovanie. Disketa obsahuje iba základ; archivátory a pomôcky OS/2 sú v úplnom ZIP vydaní.</p>
  </topic>
  <topic id="panels" layout="prose">
    <title>Panely a nastavenia</title>
    <p>Program používa panely verzie 4.99. Quick View ukazuje súbor druhého panela a odlišuje sa od úplného prehliadača F3. Aktuálne režimy zobrazenia a nastavenia sú priamo v menu F9 programu VC.</p>
    <p>Popisy súborov spracúva VC, samostatné TSR FILES_NC alebo RESINFO nie sú potrebné. Farby sa tiež nastavujú vo VC bez programu VC-COLOR. F9, Options otvorí nastavenia, Shift-F9 ich uloží. Referenčné kapitoly opisujú funkčné nastavenia a označujú nedokončené body menu. Preložené referenčné stránky ku klávesom, kopírovaniu, hľadaniu, prehliadaču a editoru zostali za novými.</p>
    <p>Pri načítanom MAXTEXT VC raz pri štarte vyberie najlepší oznámený textový režim: 80x50, potom 80x43, potom 80x25. Bez kompatibilného ovládača, dostatočnej pracovnej pamäte alebo povoleného prepnutia zostáva bežná obrazovka. MAXTEXT je voliteľný a neinštaluje sa s VC.</p>
  </topic>
  <topic id="names" layout="prose">
    <title>Dlhé názvy a cesty DOS</title>
    <p>VC používa dlhé názvy, ak systém alebo nainštalovaný ovládač poskytuje rozhranie LFN. V čistom DOS použite existujúci DOSLFN. Nový ovládač LFN ani NTFS nie je súčasťou balíka.</p>
    <p>Menu odovzdáva malým DOS nástrojom krátke názvy: !~.! je názov súboru, !~@ zoznam označených krátkych názvov. !@ môže vytvoriť textový zoznam dlhých názvov známych VC. Retro7Zip používa dostupné rozhranie LFN. Obmedzenia archivátora, súborového systému, veľkosti a pamäte DOS platia naďalej.</p>
  </topic>
  <topic id="helpbuild" layout="prose">
    <title>Ako zostaviť vlastnú pomoc</title>
    <p>Zdroje UTF-8: help/src/sk.xml. XMLmind používa guide.dtd a guide.css. Pôvod: help/SOURCES.TXT.</p>
    <pre>make help
make release</pre>
    <p>make help vytvorí päť jazykových súborov a mapu kontextu v build/help. Verzia pochádza z VcVersion v src/VCDATA.INC. Náhľad pripravovanej 5.0:</p>
    <pre>python3 tools/hlp.py build --version 5.0 --output build/help50</pre>
