=== geosone/vc/assets/charsets.dtd
<!ELEMENT charsets (table+)>
<!ATTLIST charsets format CDATA #FIXED "vc-tbl-v1" origin CDATA #REQUIRED
          archive-url CDATA #REQUIRED archive-sha256 CDATA #REQUIRED>
<!ELEMENT table (unicode | (to-external, to-dos))>
<!ATTLIST table file CDATA #REQUIRED title CDATA #REQUIRED
          kind (unicode | single-byte) #REQUIRED dos-codepage CDATA #REQUIRED
          original-sha256 CDATA #REQUIRED>
<!ELEMENT unicode (override*)>
<!ATTLIST unicode codec CDATA #REQUIRED>
<!ELEMENT override EMPTY>
<!ATTLIST override byte CDATA #REQUIRED codepoint CDATA #REQUIRED reason CDATA #REQUIRED>
<!ELEMENT to-external (row+)>
<!ELEMENT to-dos (row+)>
<!ELEMENT row (#PCDATA)>
<!ATTLIST row first CDATA #REQUIRED>

=== geosone/vc/assets/charsets.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE charsets SYSTEM "charsets.dtd">
<charsets format="vc-tbl-v1" origin="Volkov Commander 4.99.08 distribution" archive-url="https://vc.vvv.kyiv.ua/download/vc49908a.zip" archive-sha256="d64df4281aa6f2384688cc10da16ff7312ccae07ba998c0a3e2a0e832d225985">
  <table file="CP437/CP437UNI.TBL" title="Unicode (United States)" kind="unicode" dos-codepage="cp437" original-sha256="ca2197bbef1ad24204e11635458ea3ab018b41473cc194d5b10baeb6d1296d55">
    <unicode codec="cp437">
      <override byte="E6" codepoint="03BC" reason="Historical table uses Greek mu instead of micro sign." />
    </unicode>
  </table>
  <table file="CP850/CP850UNI.TBL" title="Unicode (Multilingual)" kind="unicode" dos-codepage="cp850" original-sha256="573a7223fd0f41cfde6a9da9b084dcfda059cec9644036213fd792bb9846646e">
    <unicode codec="cp850">
      <override byte="D5" codepoint="20AC" reason="Historical Euro variant: Euro sign instead of dotless i." />
    </unicode>
  </table>
  <table file="CP852/CP1250.TBL" title="CP-1250 (Windows CE)" kind="single-byte" dos-codepage="cp852" original-sha256="ed2c52e14753e24db07a35ddfc6cb25571f3c2e3511403a3bf87ce3ea5a06e4b">
    <to-external>
      <row first="80">C7 FC E9 E2 E4 F9 E6 E7 B3 EB D5 F5 EE 8F C4 C6</row>
      <row first="90">C9 C5 E5 F4 F6 BC BE 8C 9C D6 DC 8D 9D A3 D7 E8</row>
      <row first="A0">E1 ED F3 FA A5 B9 8E 9E CA EA A0 9F C8 BA AB BB</row>
      <row first="B0">00 00 00 00 00 C1 C2 CC AA 00 00 00 00 AF BF 00</row>
      <row first="C0">00 00 00 00 97 86 C3 E3 00 00 00 00 00 00 00 A4</row>
      <row first="D0">F0 D0 CF CB EF D2 CD CE EC 00 00 00 00 DE D9 00</row>
      <row first="E0">D3 DF D4 D1 F1 F2 8A 9A C0 DA E0 DB FD DD FE B4</row>
      <row first="F0">96 BD B2 A1 A2 A7 F7 B8 B0 A8 FF FB D8 F8 00 00</row>
    </to-external>
    <to-dos>
      <row first="80">00 00 60 00 22 00 C5 C5 5E 25 E6 3C 97 9B A6 8D</row>
      <row first="90">00 60 27 22 22 07 F0 C4 7E 74 E7 3E 98 9C A7 AB</row>
      <row first="A0">AA F3 F4 9D CF A4 7C F5 F9 63 B8 AE C4 F0 52 BD</row>
      <row first="B0">F8 2B F2 88 EF 75 14 07 F7 A5 AD AF 95 F1 96 BE</row>
      <row first="C0">E8 B5 B6 C6 8E 91 8F 80 AC 90 A8 D3 B7 D6 D7 D2</row>
      <row first="D0">D1 E3 D5 E0 E2 8A 99 9E FC DE E9 EB 9A ED DD E1</row>
      <row first="E0">EA A0 83 C7 84 92 86 87 9F 82 A9 89 D8 A1 8C D4</row>
      <row first="F0">D0 E4 E5 A2 93 8B 94 F6 FD 85 A3 FB 81 EC EE FA</row>
    </to-dos>
  </table>
  <table file="CP852/CP852UNI.TBL" title="Unicode (Eastern Europe)" kind="unicode" dos-codepage="cp852" original-sha256="f49c3f24eb93dcc6f2690df1c656b2ea62c21a2cd187f5c02e4307cc21bc5bd0">
    <unicode codec="cp852">
      <override byte="AA" codepoint="FFFF" reason="Historical table marks this byte undefined with U+FFFF." />
    </unicode>
  </table>
  <table file="CP852/CP895.TBL" title="CP-895_867 (MJK)" kind="single-byte" dos-codepage="cp852" original-sha256="9a682c05e964ec15c9775cfeb6784cd7585f0e4c29b065c9d43a9416c9d8a089">
    <to-external>
      <row first="80">00 81 82 00 84 96 00 00 00 00 00 00 00 00 8E 00</row>
      <row first="90">90 8A 8D 93 94 9C 8C 00 00 99 9A 86 9F 00 00 87</row>
      <row first="A0">A0 A1 A2 A3 00 00 92 91 00 00 00 00 AC 00 AE AF</row>
      <row first="B0">B0 B1 B2 B3 B4 8F 00 89 00 B9 BA BB BC 00 00 BF</row>
      <row first="C0">C0 C1 C2 C3 C4 C5 00 00 C8 C9 CA CB CC CD CE 00</row>
      <row first="D0">00 00 85 00 83 A5 8B 00 88 D9 DA DB DC 00 A6 DF</row>
      <row first="E0">95 E1 A7 00 00 A4 9B A8 AB 97 AA 00 98 9D 00 00</row>
      <row first="F0">00 00 00 00 00 AD F6 00 F8 00 00 00 9E A9 FE FF</row>
    </to-external>
    <to-dos>
      <row first="80">AC 81 82 D4 84 D2 9B 9F D8 B7 91 D6 96 92 8E B5</row>
      <row first="90">90 A7 A6 93 94 E0 85 E9 EC 99 9A E6 95 ED FC 9C</row>
      <row first="A0">A0 A1 A2 A3 E5 D5 DE E2 E7 FD EA E8 AC F5 AE AF</row>
      <row first="B0">B0 B1 B2 B3 B4 B4 B9 BB BB B9 BA BB BC BC BC BF</row>
      <row first="C0">C0 C1 C2 C3 C4 C5 C3 CC C8 C9 CA CB CC CD CE CA</row>
      <row first="D0">C1 CB C2 C8 C8 C9 C9 CE CE D9 DA DB DC DB DB DF</row>
      <row first="E0">00 E1 00 00 00 00 75 00 00 00 00 00 00 00 00 00</row>
      <row first="F0">3D 2B 3E 3C B3 B3 F6 7E F8 07 07 00 6E 32 FE FF</row>
    </to-dos>
  </table>
  <table file="CP852/CP896.TBL" title="CP-896 (Mazowia)" kind="single-byte" dos-codepage="cp852" original-sha256="3fe52bd2456701f1d9731ed2e59988a4fa003e9bd76c484874bc7e5dffac3e88">
    <to-external>
      <row first="80">80 81 82 83 84 00 8D 87 92 89 00 00 8C A0 8E 95</row>
      <row first="90">00 00 00 93 94 00 00 98 9E 99 9A 00 00 9C 00 00</row>
      <row first="A0">00 00 A2 00 8F 86 00 00 90 91 00 A6 00 00 AE AF</row>
      <row first="B0">B0 B1 B2 B3 B4 00 00 00 00 B9 BA BB BC A1 A7 BF</row>
      <row first="C0">C0 C1 C2 C3 C4 C5 00 00 C8 C9 CA CB CC CD CE 00</row>
      <row first="D0">00 00 00 00 00 00 00 00 00 D9 DA DB DC 00 00 DF</row>
      <row first="E0">A3 E1 00 A5 A4 00 00 00 00 00 00 00 00 00 00 00</row>
      <row first="F0">00 00 00 00 00 00 F6 00 F8 00 00 00 00 00 FE FF</row>
    </to-external>
    <to-dos>
      <row first="80">80 81 82 83 84 61 A5 87 65 89 65 69 8C 86 8E A4</row>
      <row first="90">A8 A9 88 93 94 8F 75 75 97 99 9A 63 9D 59 98 00</row>
      <row first="A0">8D BD A2 E0 E4 E3 AB BE 3F DA BF 00 00 21 AE AF</row>
      <row first="B0">B0 B1 B2 B3 B4 B4 B9 BB BB B9 BA BB BC BC BC BF</row>
      <row first="C0">C0 C1 C2 C3 C4 C5 C3 CC C8 C9 CA CB CC CD CE CA</row>
      <row first="D0">C1 CB C2 C8 C8 C9 C9 CE CE D9 DA DB DC DB DB DF</row>
      <row first="E0">00 E1 00 00 00 00 75 00 00 00 00 00 00 00 00 00</row>
      <row first="F0">3D 2B 3E 3C B3 B3 F6 7E F8 07 07 00 6E 32 FE FF</row>
    </to-dos>
  </table>
  <table file="CP852/CWI.TBL" title="CWI" kind="single-byte" dos-codepage="cp852" original-sha256="ba6f78db0c66e0196d0b157c8243bca54e82c16d8dca17cddf5e0516b5f6853b">
    <to-external>
      <row first="80">80 81 82 83 84 00 00 87 00 89 A7 93 8C 00 8E 00</row>
      <row first="90">90 00 00 00 94 00 00 00 00 99 9A 00 00 9C 00 00</row>
      <row first="A0">A0 A1 A2 00 00 00 00 00 00 00 00 00 00 00 AE AF</row>
      <row first="B0">B0 B1 B2 B3 B4 8F 00 00 00 B9 BA BB BC 00 00 BF</row>
      <row first="C0">C0 C1 C2 C3 C4 C5 00 00 C8 C9 CA CB CC CD CE 00</row>
      <row first="D0">00 00 00 00 00 00 8D 00 00 D9 DA DB DC 00 00 DF</row>
      <row first="E0">95 E1 00 A5 A4 00 00 00 00 97 00 98 00 00 00 00</row>
      <row first="F0">00 00 00 00 00 00 F6 00 F8 00 00 96 00 00 FE FF</row>
    </to-external>
    <to-dos>
      <row first="80">80 81 82 83 84 61 61 87 65 89 65 69 8C D6 8E B5</row>
      <row first="90">90 61 41 8B 94 E0 FB E9 EB 99 9A 63 9D 59 50 00</row>
      <row first="A0">A0 A1 A2 E0 E4 E3 61 8A 3F DA BF 00 00 21 AE AF</row>
      <row first="B0">B0 B1 B2 B3 B4 B4 B9 BB BB B9 BA BB BC BC BC BF</row>
      <row first="C0">C0 C1 C2 C3 C4 C5 C3 CC C8 C9 CA CB CC CD CE CA</row>
      <row first="D0">C1 CB C2 C8 C8 C9 C9 CE CE D9 DA DB DC DB DB DF</row>
      <row first="E0">00 E1 00 00 00 00 75 00 00 00 00 00 00 00 00 00</row>
      <row first="F0">3D 2B 3E 3C B3 B3 F6 7E F8 07 07 00 6E 32 FE FF</row>
    </to-dos>
  </table>
  <table file="CP852/ISO88592.TBL" title="ISO 8859-2 (Latin 2)" kind="single-byte" dos-codepage="cp852" original-sha256="b4ea4871af7ca014fbfe1585537e2e7f00916e2b8a910dcb060d939547385c95">
    <to-external>
      <row first="80">C7 FC E9 E2 E4 F9 E6 E7 B3 EB D5 F5 EE AC C4 C6</row>
      <row first="90">C9 C5 E5 F4 F6 A5 B5 A6 B6 D6 DC AB BB A3 D7 E8</row>
      <row first="A0">E1 ED F3 FA A1 B1 AE BE CA EA A0 BC C8 BA 00 00</row>
      <row first="B0">00 00 00 00 00 C1 C2 CC AA 00 00 00 00 AF BF 00</row>
      <row first="C0">00 00 00 00 00 00 C3 E3 00 00 00 00 00 00 00 A4</row>
      <row first="D0">F0 D0 CF CB EF D2 CD CE EC 00 00 00 00 DE D9 00</row>
      <row first="E0">D3 DF D4 D1 F1 F2 A9 B9 C0 DA E0 DB FD DD FE B4</row>
      <row first="F0">AD BD B2 B7 A2 A7 F7 B8 B0 A8 FF FB D8 F8 00 00</row>
    </to-external>
    <to-dos>
      <row first="80">00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00</row>
      <row first="90">00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00</row>
      <row first="A0">AA A4 F4 9D CF 95 97 F5 F9 E6 B8 9B 8D F0 A6 BD</row>
      <row first="B0">F8 A5 F2 88 EF 96 98 F3 F7 E7 AD 9C AB F1 A7 BE</row>
      <row first="C0">E8 B5 B6 C6 8E 91 8F 80 AC 90 A8 D3 B7 D6 D7 D2</row>
      <row first="D0">D1 E3 D5 E0 E2 8A 99 9E FC DE E9 EB 9A ED DD E1</row>
      <row first="E0">EA A0 83 C7 84 92 86 87 9F 82 A9 89 D8 A1 8C D4</row>
      <row first="F0">D0 E4 E5 A2 93 8B 94 F6 FD 85 A3 FB 81 EC EE FA</row>
    </to-dos>
  </table>
  <table file="CP852/KAMENICT.TBL" title="Kamenicti" kind="single-byte" dos-codepage="cp852" original-sha256="47f54a200457611f68c7fb204724ec407b5ee910498ab667df7887ce74dfa0a9">
    <to-external>
      <row first="80">00 81 82 00 84 96 00 00 00 00 00 00 00 00 8E 00</row>
      <row first="90">90 8A 8D 93 94 95 8C 00 00 99 9A 86 9F 00 00 87</row>
      <row first="A0">A0 A1 A2 A3 00 00 92 91 00 00 00 00 AC AD AE AF</row>
      <row first="B0">B0 B1 B2 B3 B4 B5 B6 B7 B8 B9 BA BB BC BD BE BF</row>
      <row first="C0">C0 C1 C2 C3 C4 C5 C6 C7 C8 C9 CA CB CC CD CE CF</row>
      <row first="D0">D0 D1 D2 D3 D4 D5 D6 D7 D8 D9 DA DB DC DD DE DF</row>
      <row first="E0">E0 E1 E2 E3 E4 E5 E6 E7 E8 E9 EA EB EC ED EE EF</row>
      <row first="F0">F0 F1 F2 F3 F4 F5 F6 F7 F8 F9 FA FB FC FD FE FF</row>
    </to-external>
    <to-dos>
      <row first="80">AC 81 82 D4 84 D2 9B 9F D8 B7 91 D6 96 92 8E B5</row>
      <row first="90">90 A7 A6 93 94 95 85 E9 EC 99 9A E6 95 ED FC 9C</row>
      <row first="A0">A0 A1 A2 A3 E5 D5 DE E2 E7 FD EA E8 AC AD AE AF</row>
      <row first="B0">B0 B1 B2 B3 B4 B5 B6 B7 B8 B9 BA BB BC BD BE BF</row>
      <row first="C0">C0 C1 C2 C3 C4 C5 C6 C7 C8 C9 CA CB CC CD CE CF</row>
